services:
  app:
    image: ghcr.io/eca-kubi/arl-kpi-app:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - ALEMBIC_DATABASE_URL=mysql+pymysql://alembic_user:${ALEMBIC_PASSWORD}@db/${MYSQL_DATABASE}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ALEMBIC_PASSWORD=${ALEMBIC_PASSWORD}
      - APP_URL=${APP_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SEED_DB=${SEED_DB}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER}
      - APP_NAME=${APP_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM=${RESEND_FROM}
      - SMS_ONLINE_GH_API_KEY=${SMS_ONLINE_GH_API_KEY}
      - SMS_ONLINE_GH_SENDER_ID=${SMS_ONLINE_GH_SENDER_ID}
      - SMS_ONLINE_GH_RECIPIENT=${SMS_ONLINE_GH_RECIPIENT}
      - SIMULATE_NOTIFICATIONS=${SIMULATE_NOTIFICATIONS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - arl-kpi-network

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ALEMBIC_PASSWORD: ${ALEMBIC_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
     # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # DB users will be created manually on first run
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - arl-kpi-network
      - coolify

volumes:
  db_data:

networks:
  arl-kpi-network:
    driver: bridge
  coolify:
    external: true
