"""Add audit fields to KPIRecord

Revision ID: 38070cf89022
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 05:31:41.991704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38070cf89022'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpirecord', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('kpirecord', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('kpirecord', sa.Column('last_modification', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'kpirecord', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kpirecord', type_='foreignkey')
    op.drop_column('kpirecord', 'last_modification')
    op.drop_column('kpirecord', 'created_at')
    op.drop_column('kpirecord', 'created_by_user_id')
    # ### end Alembic commands ###
