"""Add composite index to KPIRecord

Revision ID: l8g9h0i1j2k3
Revises: k7f8g9h0i1j2
Create Date: 2026-06-24 21:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'l8g9h0i1j2k3'
down_revision: Union[str, Sequence[str], None] = 'k7f8g9h0i1j2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_kpirecord_dept_date_metric_subtype',
        'kpirecord',
        ['department', 'date', 'metric_name', 'subtype']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kpirecord_dept_date_metric_subtype', table_name='kpirecord')
    # ### end Alembic commands ###
