name: Build and Push to GHCR

on:
  push:
    branches:
      - master # Change this if your default branch is 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub provides this automatically

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/arl-kpi-app:latest

      - name: Trigger Coolify Deployment Softenprise
        run: |
          curl -k -X GET "https://coolify.softenprise.com/api/v1/deploy?uuid=wexx5afvrw8rbuvibohw3lsr&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN_SOFTENPRISE }}"

      # - name: Trigger Coolify Deployment ARL
      #   run: |
      #     curl -k -X GET "https://coolify.adamusgh.com/api/v1/deploy?uuid=c8kgccc40oo08osoggc0004s&force=false" \
      #       -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN_ARL }}"